### ISSUE TITLE
Temporary files not being removed

### ISSUE THREAD

**Issue by orthes** [nacmartin/phpexecjs#4] opened 2016-06-23 07:29 UTC
Is it possible that temporary files are not being removed correctly?

Everything was going well, until one day the server ran out off the storage space. I narrowed it down to huge `/tmp` folder and there dozens of `nacmartin_phpexecjs....js` files (around 5GB). When I removed all of them manually and watched `/tmp` for a while, every time JS was executed, tmp file was created and correctly removed after that. But after some time, when I come back to `/tmp` I see a few `nacmartin_phpexecjs....js` files that were not removed (all one day old, because that's when I removed the files manually):

```
-rw-r--r--  1 user    psacln        81217806 Jun 22 18:07 nacmartin_phpexecjs576ab7c9344232.18109975.js
-rw-r--r--  1 user    psacln        81338174 Jun 22 22:11 nacmartin_phpexecjs576af10d982475.07614149.js
-rw-r--r--  1 user    psacln        81338174 Jun 22 22:12 nacmartin_phpexecjs576af12c09bd17.44509115.js
-rw-r--r--  1 user    psacln        81338174 Jun 22 22:12 nacmartin_phpexecjs576af14b2a0762.29969885.js
-rw-r--r--  1 user    psacln        81338174 Jun 22 22:13 nacmartin_phpexecjs576af16999c129.82877173.js
-rw-r--r--  1 user    psacln        81338174 Jun 22 22:14 nacmartin_phpexecjs576af18883b2a4.37265263.js
-rw-r--r--  1 user    psacln        81338174 Jun 22 22:14 nacmartin_phpexecjs576af1a6eb3912.49318189.js
```

Now there are 7 files around 77MB each = 500MB. So if I leave it like this, 7 files will become 70 files after few days and 500MB will become 5GB etc.

Is there anything that can be done in the library to prevent this? Or should I write a custom cron script that would delete all old `nacmartin_phpexecjs....js` files once a day?

**Comment by nacmartin** [comment] 2016-06-26 16:44
Hi, orthes. Thanks for the report.

This is interesting, but I cannot reproduce it. There is a call to `https://github.com/nacmartin/phpexecjs/blob/master/src/Nacmartin/PhpExecJs/Runtime/ExternalRuntime.php#L170` that removes the temporary files created.

It is ensured to run both here:
https://github.com/nacmartin/phpexecjs/blob/master/src/Nacmartin/PhpExecJs/Runtime/ExternalRuntime.php#L58

and here:
https://github.com/nacmartin/phpexecjs/blob/master/src/Nacmartin/PhpExecJs/Runtime/ExternalRuntime.php#L63

It would be interesting to know why in your case this is not working.

**Comment by nacmartin** [comment] 2016-09-13 14:27
Since there is no answer, I close this report. Please, reopen if if you have more information.

**Closed by nacmartin** 2016-09-13 14:27 UTC
